import { it,expect,vi,beforeEach } from 'vitest';
const mocks=vi.hoisted(()=>({publer:vi.fn(),research:vi.fn(),generate:vi.fn(),audit:vi.fn()}));
vi.mock('../lib/publer',()=>({publer:mocks.publer,jobResult:v=>v,failures:v=>Boolean(v&&Object.keys(v).length)}));
vi.mock('../lib/ai',()=>({researchStep:mocks.research,generatePlatform:mocks.generate,audit:mocks.audit}));
import { auditDigest,step,importStep,deliver,checkDelivery,validateAll } from '../lib/engine';
import fixture from '../config/sample-content.json';
function job(){return {id:'test',brief:{topic:'Pharma visual aid',primary_keyword:'pharma visual aid printing',language:'hinglish',platforms:['facebook'],cta_url:'https://rxdesignhub.com',notes:'',targets:{facebook:['a']},boards:{}},media:[{url:'https://store.public.blob.vercel-storage.com/media/test/1.png',pathname:'media/test/1.png',name:'1.png',type:'image',width:1080,height:1080,duration:0,size:1000}],content:{facebook:structuredClone(fixture.facebook)},research:{facts:[]},status:'ready',audit:{approved:true}};}
beforeEach(()=>{vi.clearAllMocks();process.env.PUBLER_WORKSPACE_ID='test-ws';});
it('audit signature survives media import transport fields but changes on copy edit',()=>{const j=job(),d=auditDigest(j);j.media[0].import_job_id='id';j.media[0].import_state='complete';j.media[0].publer={id:'media'};expect(auditDigest(j)).toBe(d);j.content.facebook.text+=' edited';expect(auditDigest(j)).not.toBe(d);});
it('does one research phase at a time',async()=>{const j=job();j.research=null;j.content={};mocks.research.mockImplementation(async j=>{j.research={facts:[]};});await step(j,vi.fn());expect(mocks.research).toHaveBeenCalledTimes(1);expect(mocks.generate).not.toHaveBeenCalled();});
it('records model failures durably',async()=>{const j=job();j.research=null;const save=vi.fn();mocks.research.mockRejectedValueOnce(new Error('Research unavailable'));await expect(step(j,save)).rejects.toThrow();expect(j.status).toBe('needs_attention');expect(save).toHaveBeenCalledTimes(2);});
it('imports once then polls saved ID, without resubmission',async()=>{const j=job();j.audit_digest=auditDigest(j);const save=vi.fn();mocks.publer.mockResolvedValueOnce({job_id:'import1'}).mockResolvedValueOnce({status:'complete',payload:{media:[{id:'m',validity:{facebook:true}}]}});await importStep(j,save);await importStep(j,save);await importStep(j,save);expect(mocks.publer).toHaveBeenCalledTimes(2);expect(mocks.publer.mock.calls[1][0]).toBe('GET');expect(j.media[0].publer.id).toBe('m');});
it('halts an ambiguous import',async()=>{const j=job();j.audit_digest=auditDigest(j);mocks.publer.mockRejectedValueOnce(Object.assign(new Error('Timeout'),{ambiguous:true}));await expect(importStep(j,vi.fn())).rejects.toThrow();expect(j.media[0].import_state).toBe('ambiguous');await expect(importStep(j,vi.fn())).rejects.toThrow(/uncertain/);expect(mocks.publer).toHaveBeenCalledTimes(1);});
it('requires explicit confirmation to publish now',async()=>{await expect(deliver(job(),vi.fn(),{mode:'now'},[])).rejects.toThrow(/Confirm/);expect(mocks.publer).not.toHaveBeenCalled();});
it('rejects missing/past scheduled time',async()=>{await expect(deliver(job(),vi.fn(),{mode:'schedule',scheduled_at:'bad'},[])).rejects.toThrow(/minute/);});
it('checks audit and prevents a second post submission',async()=>{const j=job();j.media[0].publer={id:'m',validity:{facebook:true}};j.audit_digest=auditDigest(j);mocks.publer.mockResolvedValueOnce({job_id:'send1'});await deliver(j,vi.fn(),{mode:'draft'},[{id:'a',provider:'facebook',status:'active'}]);expect(j.delivery.job_id).toBe('send1');await expect(deliver(j,vi.fn(),{mode:'draft'},[])).rejects.toThrow(/already exists/);expect(mocks.publer).toHaveBeenCalledTimes(1);});
it('does not require image alt text for video platforms when a separate image exists',()=>{const j=job();j.brief={...j.brief,platforms:['linkedin'],targets:{linkedin:['li']}};j.media=[{type:'video',width:1080,height:1920,duration:60,size:1000,url:'https://x.test/v.mp4',pathname:'v.mp4',publer:{id:'v',validity:{linkedin:{video:true}}}},{type:'image',width:1080,height:1080,duration:0,size:1000,url:'https://x.test/i.png',pathname:'i.png',publer:{id:'i',validity:{google:{photo:true},pinterest:{photo:true}}}}];j.content={linkedin:{text:'pharma visual aid printing needs clear layout.\n\nhttps://rxdesignhub.com\n\n#VisualAid #PharmaMarketing #PrintDesign'}};expect(()=>validateAll(j)).not.toThrow();});
it('turns completed partial failures into needs_attention',async()=>{const j=job();j.delivery={job_id:'x',status:'working',mode:'draft'};mocks.publer.mockResolvedValueOnce({status:'complete',payload:{failures:[{message:'Invalid account'}]}});await checkDelivery(j);expect(j.status).toBe('needs_attention');expect(j.delivery.status).toBe('failed');});
it('records a Publer draft completion and does not poll again',async()=>{const j=job();j.delivery={job_id:'x',status:'working',mode:'draft'};mocks.publer.mockResolvedValueOnce({status:'complete',payload:{failures:{}}});await checkDelivery(j);await checkDelivery(j);expect(j.status).toBe('publer_draft');expect(mocks.publer).toHaveBeenCalledTimes(1);});
