import { it,expect } from 'vitest';
import { briefSchema,selectType,validFor,validateMediaSet,buildPayload,assertEditable } from '../lib/model';
const brief={topic:'Visual aid printing',primary_keyword:'visual aid printing',language:'english',platforms:['facebook'],cta_url:'https://rxdesignhub.com',notes:'',targets:{facebook:['fb']},boards:{}};
const m={type:'image',width:1080,height:1080,publer:{id:'m1',validity:{facebook:{photo:true},instagram:{photo:true},google:{photo:true},pinterest:{photo:true}}}};
const job={brief,media:[m],content:{facebook:{text:'Caption',alt_texts:['Image one']}}};
const accounts=[{id:'fb',provider:'facebook',status:'active'},{id:'ig',provider:'instagram',status:'active'},{id:'g',provider:'google',status:'active'},{id:'pin',provider:'pinterest',status:'active'}];
it('rejects empty briefs, insecure CTA URL and unknown platforms',()=>{expect(()=>briefSchema.parse({...brief,topic:''})).toThrow();expect(()=>briefSchema.parse({...brief,cta_url:'javascript:alert(1)'})).toThrow();expect(()=>briefSchema.parse({...brief,platforms:['unknown']})).toThrow();});
it('selects compatible formats and caps image counts',()=>{expect(selectType('youtube',[m])).toBeNull();expect(selectType('linkedin',Array(10).fill(m)).count).toBe(9);expect(selectType('twitter',Array(10).fill(m)).count).toBe(4);expect(selectType('google',Array(3).fill(m)).count).toBe(1);});
it('uses video+format for reels/shorts, skips Google video',()=>{const v={type:'video',width:1080,height:1920,duration:60};expect(selectType('instagram',[v])).toMatchObject({type:'video',format:'reel'});expect(selectType('youtube',[v]).format).toBe('short');expect(selectType('youtube',[{...v,duration:180}]).format).toBe('short');expect(selectType('youtube',[{...v,duration:181}]).format).toBeUndefined();expect(selectType('google',[v])).toBeNull();});
it('rejects unsupported video duration or aspect',()=>{const v={type:'video',width:1920,height:1080,duration:150};expect(selectType('instagram',[v])).toBeNull();expect(selectType('twitter',[v])).toBeNull();expect(selectType('tiktok',[v])).toBeNull();});
it('allows one video plus images but rejects too many assets',()=>{expect(()=>validateMediaSet([])).toThrow();expect(()=>validateMediaSet(Array(11).fill(m))).toThrow();expect(()=>validateMediaSet([m,{type:'video'},{type:'video'}])).toThrow();expect(()=>validateMediaSet([m,{type:'video'}])).not.toThrow();});
it('fails closed on unknown/false validity',()=>{expect(validFor({},'instagram','reel')).toBe(false);expect(validFor({validity:{instagram:{video:true,reel:false}}},'instagram','reel')).toBe(false);});
it('creates draft without a schedule and immediate with correct endpoint',()=>{expect(buildPayload(job,'draft',null,accounts).payload.bulk.state).toBe('draft');const now=buildPayload(job,'now',null,accounts);expect(now.endpoint).toBe('/posts/schedule/publish');expect(now.payload.bulk.posts[0].accounts).toEqual([{id:'fb'}]);});
it('places schedule on accounts and rejects mismatched account providers',()=>{expect(buildPayload(job,'schedule','2027-01-01T10:00:00+05:30',accounts).payload.bulk.posts[0].accounts[0].scheduled_at).toContain('+05:30');expect(()=>buildPayload({...job,brief:{...brief,targets:{facebook:['ig']}}},'draft',null,accounts)).toThrow(/Invalid/);});
it('places Instagram comment and Pinterest board on accounts',()=>{const j={...job,brief:{...brief,platforms:['instagram','pinterest','google'],targets:{instagram:['ig'],pinterest:['pin'],google:['g']},boards:{pin:'board1'}},content:{instagram:{caption:'hello',first_comment_hashtags:'#Print'},pinterest:{description:'desc',title:'Title'},google:{text:'hello'}}};const p=buildPayload(j,'draft',null,accounts).payload.bulk.posts[0];expect(p.accounts.find(a=>a.id==='pin').album_id).toBe('board1');expect(p.accounts.find(a=>a.id==='ig').comments[0].text).toBe('#Print');expect(p.networks.google.title).toBe('LEARN_MORE');});
it('uses video for video platforms and image for Pinterest/Google in one daily post',()=>{
  const video={type:'video',width:1080,height:1920,duration:60,publer:{id:'v1',validity:{instagram:{reel:true},facebook:{video:true},youtube:{short:true}}}};
  const image={...m,publer:{id:'i1',validity:{google:{photo:true},pinterest:{photo:true}}}};
  const j={brief:{...brief,platforms:['instagram','google','pinterest'],targets:{instagram:['ig'],google:['g'],pinterest:['pin']},boards:{pin:'board1'}},media:[video,image],content:{instagram:{caption:'reel'},google:{text:'gbp'},pinterest:{description:'pin',title:'Pin'}}};
  const p=buildPayload(j,'draft',null,accounts).payload.bulk.posts[0];
  expect(p.networks.instagram.media[0]).toMatchObject({id:'v1',type:'video'});
  expect(p.networks.google.media[0]).toMatchObject({id:'i1',type:'image'});
  expect(p.networks.pinterest.media[0]).toMatchObject({id:'i1',type:'image'});
});
it('prevents edits once delivery begins',()=>expect(()=>assertEditable({delivery:{status:'working'}})).toThrow(/delivery/));
