import { it,expect,beforeEach,afterEach,vi } from 'vitest';
import { inspectReset,performReset,resetTables } from '../lib/reset';
const original={...process.env};
beforeEach(()=>{delete process.env.PUBLER_API_KEY;delete process.env.PUBLER_WORKSPACE_ID;});
afterEach(()=>{process.env={...original};});
function mockSql(seed={}){const calls=[];const sql=vi.fn(async(strings,...values)=>{const query=strings.join('?').replace(/\s+/g,' ').trim();calls.push({query,values});const found=query.match(/^SELECT \* FROM (\w+)/i);return found?structuredClone(seed[found[1]]??[]):[];});return {sql,calls};}
it('dry run only reads counts and changes nothing',async()=>{const {sql,calls}=mockSql({rx_jobs:[{id:'1'}],rx_settings:[{id:'connections'}]});const report=await inspectReset({sql,publerClient:vi.fn()});expect(report.counts.rx_jobs).toBe(1);expect(calls.every(c=>c.query.startsWith('SELECT'))).toBe(true);});
it('confirm requires exact RESET',async()=>{const {sql}=mockSql();await expect(performReset({sql,confirm:'reset'})).rejects.toThrow(/RESET exactly/);expect(sql).not.toHaveBeenCalled();});
it('creates the backup before any destructive query',async()=>{const events=[],base=mockSql({rx_jobs:[{id:'1'}]});const sql=vi.fn(async(...args)=>{const query=args[0].join('?').replace(/\s+/g,' ').trim();if(query.startsWith('TRUNCATE')||query.startsWith('DELETE'))events.push('delete');return base.sql(...args);});await performReset({sql,confirm:'RESET',includePubler:false,onBackup:async backup=>{expect(backup.tables.rx_jobs).toHaveLength(1);events.push('backup');}});expect(events[0]).toBe('backup');});
it('keeps connections unless all is true',async()=>{const one=mockSql();await performReset({sql:one.sql,confirm:'RESET',includePubler:false});expect(one.calls.some(c=>c.query==="DELETE FROM rx_settings WHERE id='channels'")).toBe(true);const two=mockSql();await performReset({sql:two.sql,confirm:'RESET',all:true,includePubler:false});expect(two.calls.some(c=>c.query==='DELETE FROM rx_settings')).toBe(true);});
it('does not abort database wipe when Publer deletion fails',async()=>{process.env.PUBLER_API_KEY='key';process.env.PUBLER_WORKSPACE_ID='workspace';const client=vi.fn(async(method,path)=>{if(method==='GET')return path.includes('scheduled')?{posts:[{id:'post-1'}]}:{posts:[]};throw new Error('plan denied');});const {sql,calls}=mockSql();const result=await performReset({sql,confirm:'RESET',publerClient:client});expect(calls.some(c=>c.query.startsWith('TRUNCATE TABLE'))).toBe(true);expect(result.summary.publer_errors.join(' ')).toMatch(/post-1/);expect(result.summary.manual_publer_cleanup).toContain('post-1');});
it('backs up every reset table and settings',async()=>{const {sql}=mockSql();const result=await performReset({sql,confirm:'RESET',includePubler:false});expect(Object.keys(result.backup.tables)).toEqual([...resetTables,'rx_settings']);});
