import { readFile,mkdir,writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

async function loadEnv(){try{const raw=await readFile(resolve('.env.local'),'utf8');for(const line of raw.split(/\r?\n/)){const value=line.trim();if(!value||value.startsWith('#'))continue;const at=value.indexOf('=');if(at<1)continue;const key=value.slice(0,at).trim(),parsed=value.slice(at+1).trim().replace(/^(['"])(.*)\1$/,'$2');if(process.env[key]===undefined)process.env[key]=parsed;}}catch(e){if(e.code!=='ENOENT')throw e;}}
await loadEnv();
const [{neon},{list,del},{databaseUrl,init},{inspectReset,performReset}]=await Promise.all([import('@neondatabase/serverless'),import('@vercel/blob'),import('../lib/db.js'),import('../lib/reset.js')]);
const url=databaseUrl();if(!url)throw new Error('No database URL found. Add DATABASE_URL to .env.local.');
await init();const sql=neon(url),args=new Set(process.argv.slice(2)),confirmed=args.has('--confirm'),all=args.has('--all'),includeBlob=args.has('--blob');
if(!confirmed){const report=await inspectReset({sql});console.log('RX Studio fresh-start dry run (nothing changed)');console.table(report.counts);console.log(`Publer scheduled/draft posts found: ${report.publer.posts.length}`);for(const post of report.publer.posts)console.log(`- ${post.id} [${post.state??post.reset_state}] ${String(post.text??post.title??'').slice(0,100)}`);for(const error of report.publer.errors)console.warn(`Publer listing warning: ${error}`);console.log('Run npm run reset -- --confirm to create a backup and wipe. Add --all for connection settings and --blob for media/pool blobs.');process.exit(0);}
let backupPath='';const result=await performReset({sql,confirm:'RESET',all,includePubler:true,includeBlob,blobList:list,blobDelete:del,onBackup:async backup=>{await mkdir(resolve('backups'),{recursive:true});backupPath=resolve('backups',`rx-backup-${backup.created_at.replace(/[:.]/g,'-')}.json`);await writeFile(backupPath,JSON.stringify(backup,null,2),'utf8');console.log(`Backup written before deletion: ${backupPath}`);}});
console.log('Fresh start complete.');console.table(result.summary.database);console.log(`Publer deleted: ${result.summary.publer_deleted.length}/${result.summary.publer_found}`);console.log(`Blob files deleted: ${result.summary.blob_deleted.length}`);if(result.summary.publer_errors.length)console.warn(`Delete remaining scheduled posts manually in Publer → Calendar (${result.summary.manual_publer_cleanup.length}): ${result.summary.manual_publer_cleanup.join(', ')||'IDs unavailable'}`);console.log(`Backup: ${backupPath}`);
